In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

import sklearn
import sklearn.metrics as sm

from sklearn import datasets


from pylab import rcParams

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split


from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score , recall_score

In [2]:
from sklearn.linear_model import Perceptron

In [6]:
iris = datasets.load_iris()

X= iris.data
y = iris.target

x[0:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [7]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2)


In [9]:
standardize = StandardScaler()

Standarized_X_test = standardize.fit_transform(X_test)

Standarized_X_train= standardize.fit_transform(X_train)



In [10]:
Standarized_X_test[0:10]

array([[-0.37486064,  1.76021608, -1.10450906, -1.10851934],
       [-0.1221456 , -1.31317708,  0.51320623,  0.07075655],
       [-1.51207831,  0.36321919, -1.21607563, -1.10851934],
       [-1.00664823,  0.92201795, -0.88137591, -1.10851934],
       [ 1.64685966,  0.08381981,  0.90368923,  1.36796004],
       [ 0.13056944, -0.19557956,  0.40163966,  0.07075655],
       [-0.50121816, -1.0337777 ,  0.2342898 ,  0.30661173],
       [-0.1221456 , -2.15137521,  0.29007309,  0.18868414],
       [-1.00664823,  0.08381981, -1.04872577, -1.10851934],
       [ 0.88871455,  0.92201795,  1.18260566,  1.48588763]])

In [12]:
perceptron = Perceptron(max_iter= 50 , eta0 = 0.15 , tol=1e-3  , random_state = 15)

perceptron.fit(Standarized_X_train , y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [14]:
y_pred = perceptron.predict(Standarized_X_test)

In [16]:
y_test

array([0, 1, 0, 0, 2, 1, 1, 1, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1, 0, 1, 0, 2,
       2, 2, 0, 2, 0, 2, 0, 2])

In [15]:
y_pred

array([0, 1, 0, 0, 2, 1, 1, 1, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1, 0, 1, 0, 2,
       2, 2, 1, 2, 0, 2, 1, 2])

In [17]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       1.00      0.85      0.92        13
           1       0.78      1.00      0.88         7
           2       1.00      1.00      1.00        10

    accuracy                           0.93        30
   macro avg       0.93      0.95      0.93        30
weighted avg       0.95      0.93      0.93        30

